Update CISpawntc

diff --git a/CISpawntc b/CISpawntc
--- a/CISpawntc
+++ b/CISpawntc
@@ -1,5 +1,10 @@
-#Loads variables
 
+#!/bin/bash
+#Loads variables
+#Must use Cloud1 for accounts (any way to change this?)
+#Some variables are modified later by fetching data from etcd
+. /home/ec2-user/Cloud1
+echo "loaded Config file"
 
 
 #gets data on setup from etcd
@@ -31,6 +36,9 @@ ReceiverPortK=`(curl http://127.0.0.1:4001/v2/keys/spawn-receiver/port | jq '.no
 #remember that honeypots could also live on swarm-master
 #limit that by launching a fake container locking the port used by Honepots??
 
+echo ""
+echo "$(tput setaf 1)Testing GCE VMs ( $prevgcevms ) $(tput sgr 0)"
+echo ""
 
 j=0
 while [ $j -lt $prevgcevms ]
@@ -40,13 +48,16 @@ do
    echo ""
    VMTest=`(curl http://127.0.0.1:4001/v2/keys/env-crate-$j/ip | jq '.node.value' | sed 's/.//;s/.$//')`
    REMOTEHOST=$VMTest
-   REMOTEPORT=8080
+   REMOTEPORT=$HoneypotPortK
    TIMEOUT=1
 
    if nc -w $TIMEOUT -z $REMOTEHOST $REMOTEPORT; then
     echo "$(tput setaf 2) I was able to connect to ${REMOTEHOST}:${REMOTEPORT} $(tput sgr 0)"
+    #Write test output in etcd
+    curl -L http://127.0.0.1:4001/v2/keys/DM-GCE-$j/TEST -XPUT -d value=PASSED
    else
     echo "$(tput setaf 1)Connection to ${REMOTEHOST}:${REMOTEPORT} failed. Exit code from Netcat was ($?). $(tput sgr 0)"
+    curl -L http://127.0.0.1:4001/v2/keys/DM-GCE-$j/TEST -XPUT -d value=FAILED
    fi
    
    #Increments counter for total GCE VMs
@@ -58,11 +69,49 @@ echo ""
 echo "$(tput setaf 1)Testing AWS VMs ( $prevawsvms ) $(tput sgr 0)"
 echo ""
 
+i=0
+while [ $i -lt $prevawsvms ]
+do
+    #Reads VM Name from etcd
+    
+    VMTest=`(curl http://127.0.0.1:4001/v2/keys/DM-AWS-$i/ip | jq '.node.value' | sed 's/.//;s/.$//')`
+    
+    echo ""
+    echo "$(tput setaf 1) Testing VM $VMTest $(tput sgr 0)"
+    echo ""
+    REMOTEHOST=$VMTest
+    REMOTEPORT=$HoneypotPortK
+    TIMEOUT=1
+
+   if nc -w $TIMEOUT -z $REMOTEHOST $REMOTEPORT; then
+    echo "$(tput setaf 2) I was able to connect to ${REMOTEHOST}:${REMOTEPORT} $(tput sgr 0)"
+    #Write test output in etcd
+    curl -L http://127.0.0.1:4001/v2/keys/DM-AWS-$i/TEST -XPUT -d value=PASSED
+   else
+    echo "$(tput setaf 1)Connection to ${REMOTEHOST}:${REMOTEPORT} failed. Exit code from Netcat was ($?). $(tput sgr 0)"
+    curl -L http://127.0.0.1:4001/v2/keys/DM-AWS-$i/TEST -XPUT -d value=FAILED
+   fi   
+    
+    #Increments counter for total AWS VMs
+    true $(( i++ ))
+   done
+
 
 #Tests Receiver
+REMOTEHOST=$publicipspawnreceiver
+REMOTEPORT=$ReceiverPortK
+TIMEOUT=1
+
+if nc -w $TIMEOUT -z $REMOTEHOST $REMOTEPORT; then
+    echo "I was able to connect to ${REMOTEHOST}:${REMOTEPORT}"
+    curl -L http://127.0.0.1:4001/v2/keys/spawn-receiver/TEST -XPUT -d value=PASSED
+else
+    echo "Connection to ${REMOTEHOST}:${REMOTEPORT} failed. Exit code from Netcat was ($?)."
+    curl -L http://127.0.0.1:4001/v2/keys/spawn-receiver/TEST -XPUT -d value=FAILED
+fi
 
 
-#!/bin/bash
+#TEST basic
 REMOTEHOST=8.8.8.8
 REMOTEPORT=53
 TIMEOUT=1
