Update CISpawntc

diff --git a/CISpawntc b/CISpawntc
--- a/CISpawntc
+++ b/CISpawntc
@@ -104,24 +104,43 @@ REMOTEPORT=$ReceiverPortK
 TIMEOUT=1
 
 if nc -w $TIMEOUT -z $REMOTEHOST $REMOTEPORT; then
-    echo "I was able to connect to ${REMOTEHOST}:${REMOTEPORT}"
+    echo "$(tput setaf 2) I was able to connect to ${REMOTEHOST}:${REMOTEPORT} $(tput sgr 0)"
     curl -L http://127.0.0.1:4001/v2/keys/spawn-receiver/TEST -XPUT -d value=PASSED
 else
-    echo "Connection to ${REMOTEHOST}:${REMOTEPORT} failed. Exit code from Netcat was ($?)."
+    echo "$(tput setaf 1) Connection to ${REMOTEHOST}:${REMOTEPORT} failed. Exit code from Netcat was ($?).$(tput sgr 0)"
     curl -L http://127.0.0.1:4001/v2/keys/spawn-receiver/TEST -XPUT -d value=FAILED
 fi
 
+#Tests Consul
+ConsulVMNameK=`(curl http://127.0.0.1:4001/v2/keys/consul/name | jq '.node.value' | sed 's/.//;s/.$//')`
+publicipCONSULK=`(curl http://127.0.0.1:4001/v2/keys/consul/ip | jq '.node.value' | sed 's/.//;s/.$//')`
+ConsulPortK=`(curl http://127.0.0.1:4001/v2/keys/consul/port | jq '.node.value' | sed 's/.//;s/.$//')`
 
-#TEST basic
-REMOTEHOST=8.8.8.8
-REMOTEPORT=53
+REMOTEHOST=$publicipCONSULK
+REMOTEPORT=$ConsulPortK
 TIMEOUT=1
 
 if nc -w $TIMEOUT -z $REMOTEHOST $REMOTEPORT; then
-    echo "I was able to connect to ${REMOTEHOST}:${REMOTEPORT}"
+    echo "$(tput setaf 2) I was able to connect to ${REMOTEHOST}:${REMOTEPORT} $(tput sgr 0)"
+    curl -L http://127.0.0.1:4001/v2/keys/consul/TEST -XPUT -d value=PASSED
 else
-    echo "Connection to ${REMOTEHOST}:${REMOTEPORT} failed. Exit code from Netcat was ($?)."
+    echo "$(tput setaf 1) Connection to ${REMOTEHOST}:${REMOTEPORT} failed. Exit code from Netcat was ($?).$(tput sgr 0)"
+    curl -L http://127.0.0.1:4001/v2/keys/consul/TEST -XPUT -d value=FAILED
 fi
+
+
+
+
+#TEST basic
+#REMOTEHOST=8.8.8.8
+#REMOTEPORT=53
+#TIMEOUT=1
+
+#if nc -w $TIMEOUT -z $REMOTEHOST $REMOTEPORT; then
+#    echo "I was able to connect to ${REMOTEHOST}:${REMOTEPORT}"
+#else
+#    echo "Connection to ${REMOTEHOST}:${REMOTEPORT} failed. Exit code from Netcat was ($?)."
+#fi
 
 
 
