Update CISpawntc

diff --git a/CISpawntc b/CISpawntc
--- a/CISpawntc
+++ b/CISpawntc
@@ -15,6 +15,17 @@
 #Tests Receiver
 
 
+#!/bin/bash
+REMOTEHOST=8.8.8.8
+REMOTEPORT=53
+TIMEOUT=1
+
+if nc -w $TIMEOUT -z $REMOTEHOST $REMOTEPORT; then
+    echo "I was able to connect to ${REMOTEHOST}:${REMOTEPORT}"
+else
+    echo "Connection to ${REMOTEHOST}:${REMOTEPORT} failed. Exit code from Netcat was ($?)."
+fi
+
 
 
 #Provide a status
