Update CISpawntc
GCE testing

diff --git a/CISpawntc b/CISpawntc
--- a/CISpawntc
+++ b/CISpawntc
@@ -31,6 +31,34 @@ ReceiverPortK=`(curl http://127.0.0.1:4001/v2/keys/spawn-receiver/port | jq '.no
 #remember that honeypots could also live on swarm-master
 #limit that by launching a fake container locking the port used by Honepots??
 
+
+j=0
+while [ $j -lt $prevgcevms ]
+do
+   echo ""
+   echo "Testing Honeypots on env-crate-$j "
+   echo ""
+   VMTest=`(curl http://127.0.0.1:4001/v2/keys/env-crate-$j/ip | jq '.node.value' | sed 's/.//;s/.$//')`
+   REMOTEHOST=$VMTest
+   REMOTEPORT=8080
+   TIMEOUT=1
+
+   if nc -w $TIMEOUT -z $REMOTEHOST $REMOTEPORT; then
+    echo "$(tput setaf 2) I was able to connect to ${REMOTEHOST}:${REMOTEPORT} $(tput sgr 0)"
+   else
+    echo "$(tput setaf 1)Connection to ${REMOTEHOST}:${REMOTEPORT} failed. Exit code from Netcat was ($?). $(tput sgr 0)"
+   fi
+   
+   #Increments counter for total GCE VMs
+   true $(( j++ ))
+   done
+
+
+echo ""
+echo "$(tput setaf 1)Testing AWS VMs ( $prevawsvms ) $(tput sgr 0)"
+echo ""
+
+
 #Tests Receiver
 
 
